apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: vuln-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        # Placeholder image until real API image is ready
        image: postgres:15
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: scanner
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vuln-scanner
spec:
  selector:
    app: api
  ports:
  - port: 8000
    targetPort: 8000
